issuers:
  - name: local-test
    issuer: https://test.local
    type: hs256
    hs256:
      secret: my-test-secret
  - name: rsa-test
    issuer: other.local
    type: rs256
    rs256:
      jwksUrl: http://jwks:80/jwks.json

